[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared Query = let
  Source = Json.Document(Web.Contents("https://teladochealth.my.workfront.com/attask/api/v19.0/team/search?apiKey=al7s4u94ggluu08vnh7atni3p5sagebm&fields=*")),
  #"Converted to table" = Table.FromRecords({Source}),
  #"Expanded data" = Table.ExpandListColumn(#"Converted to table", "data"),
  #"Expanded data1" = Table.ExpandRecordColumn(#"Expanded data", "data", {"ID", "name", "objCode", "agileEstimateType", "agileMethodology", "autoAddNextStory", "completeDaysOnKanbanBoard", "customerID", "description", "estimateByHours", "groupID", "hoursPerPoint", "isActive", "isAgile", "isStandardIssueList", "layoutTemplateID", "opTaskBugReportStatuses", "opTaskChangeOrderStatuses", "opTaskIssueStatuses", "opTaskRequestStatuses", "ownerID", "scheduleID", "taskStatuses", "teamStoryBoardIssueStatuses", "teamStoryBoardStatuses", "teamType", "uiTemplateID", "wipLimit", "workOnItOpTaskBugReportStatuses", "workOnItOpTaskChangeOrderStatuses", "workOnItOpTaskIssueStatuses", "workOnItOpTaskRequestStatuses", "workOnItStatusChange", "workOnItTaskStatuses"}, {"data.ID", "data.name", "data.objCode", "data.agileEstimateType", "data.agileMethodology", "data.autoAddNextStory", "data.completeDaysOnKanbanBoard", "data.customerID", "data.description", "data.estimateByHours", "data.groupID", "data.hoursPerPoint", "data.isActive", "data.isAgile", "data.isStandardIssueList", "data.layoutTemplateID", "data.opTaskBugReportStatuses", "data.opTaskChangeOrderStatuses", "data.opTaskIssueStatuses", "data.opTaskRequestStatuses", "data.ownerID", "data.scheduleID", "data.taskStatuses", "data.teamStoryBoardIssueStatuses", "data.teamStoryBoardStatuses", "data.teamType", "data.uiTemplateID", "data.wipLimit", "data.workOnItOpTaskBugReportStatuses", "data.workOnItOpTaskChangeOrderStatuses", "data.workOnItOpTaskIssueStatuses", "data.workOnItOpTaskRequestStatuses", "data.workOnItStatusChange", "data.workOnItTaskStatuses"}),
  #"Split column" = Table.SplitColumn(#"Expanded data1", "data.opTaskBugReportStatuses", each _, {"data.opTaskBugReportStatuses.0"}),
  #"Split column1" = Table.SplitColumn(#"Split column", "data.opTaskChangeOrderStatuses", each _, {"data.opTaskChangeOrderStatuses.0"}),
  #"Split column2" = Table.SplitColumn(#"Split column1", "data.opTaskIssueStatuses", each _, {"data.opTaskIssueStatuses.0"}),
  #"Split column3" = Table.SplitColumn(#"Split column2", "data.opTaskRequestStatuses", each _, {"data.opTaskRequestStatuses.0"}),
  #"Split column4" = Table.SplitColumn(#"Split column3", "data.taskStatuses", each _, {"data.taskStatuses.0"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Split column4", {{"data.ID", type text}, {"data.name", type text}, {"data.objCode", type text}, {"data.agileEstimateType", type text}, {"data.agileMethodology", type text}, {"data.autoAddNextStory", type logical}, {"data.completeDaysOnKanbanBoard", Int64.Type}, {"data.customerID", type text}, {"data.description", type text}, {"data.estimateByHours", type logical}, {"data.groupID", type text}, {"data.hoursPerPoint", Int64.Type}, {"data.isActive", type logical}, {"data.isAgile", type logical}, {"data.isStandardIssueList", type logical}, {"data.opTaskBugReportStatuses.0", type text}, {"data.opTaskChangeOrderStatuses.0", type text}, {"data.opTaskIssueStatuses.0", type text}, {"data.opTaskRequestStatuses.0", type text}, {"data.ownerID", type text}, {"data.scheduleID", type text}, {"data.taskStatuses.0", type text}, {"data.teamStoryBoardIssueStatuses", type text}, {"data.teamStoryBoardStatuses", type text}, {"data.teamType", type text}, {"data.uiTemplateID", type text}, {"data.wipLimit", Int64.Type}, {"data.workOnItStatusChange", type logical}})
in
  #"Changed column type";
