[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared Query = let
  Source = Json.Document(Web.Contents("https://teladochealth.my.workfront.com/attask/api/v19.0/user/search?apiKey=al7s4u94ggluu08vnh7atni3p5sagebm&fields=*,parameterValues")),
  #"Converted to table" = Table.FromRecords({Source}),
  #"Expanded data" = Table.ExpandListColumn(#"Converted to table", "data"),
  #"Expanded data1" = Table.ExpandRecordColumn(#"Expanded data", "data", {"ID", "name", "objCode", "accessLevelID", "actualDeactivationDate", "address", "address2", "apiKeyCreateDate", "avatarDate", "avatarSize", "avatarX", "avatarY", "billingPerHour", "categoryID", "city", "companyID", "costPerHour", "country", "customerID", "defaultHourTypeID", "defaultInterface", "delegationToID", "emailAddr", "enteredByID", "entryDate", "extRefID", "firstName", "fte", "hasAPIAccess", "hasDocuments", "hasNotes", "hasProofLicense", "hasReservedTimes", "homeGroupID", "homeTeamID", "isActive", "lastEnteredNoteID", "lastLoginDate", "lastName", "lastNoteID", "lastUpdateDate", "lastUpdatedByID", "latestUpdateNoteID", "layoutTemplateID", "licenseType", "locale", "logTimeInDays", "loginCount", "managerID", "mobilePhoneNumber", "myInfo", "passwordDate", "persona", "phoneExtension", "phoneNumber", "portalProfileID", "postalCode", "registrationExpireDate", "resetPasswordExpireDate", "resourcePoolID", "roleID", "scheduleID", "scheduledDeactivationDate", "ssoAccessOnly", "ssoUsername", "state", "statusUpdate", "timeZone", "timesheetProfileID", "title", "uiTemplateID", "username", "webDAVProfile", "workHoursPerDay", "workTime", "parameterValues"}, {"data.ID", "data.name", "data.objCode", "data.accessLevelID", "data.actualDeactivationDate", "data.address", "data.address2", "data.apiKeyCreateDate", "data.avatarDate", "data.avatarSize", "data.avatarX", "data.avatarY", "data.billingPerHour", "data.categoryID", "data.city", "data.companyID", "data.costPerHour", "data.country", "data.customerID", "data.defaultHourTypeID", "data.defaultInterface", "data.delegationToID", "data.emailAddr", "data.enteredByID", "data.entryDate", "data.extRefID", "data.firstName", "data.fte", "data.hasAPIAccess", "data.hasDocuments", "data.hasNotes", "data.hasProofLicense", "data.hasReservedTimes", "data.homeGroupID", "data.homeTeamID", "data.isActive", "data.lastEnteredNoteID", "data.lastLoginDate", "data.lastName", "data.lastNoteID", "data.lastUpdateDate", "data.lastUpdatedByID", "data.latestUpdateNoteID", "data.layoutTemplateID", "data.licenseType", "data.locale", "data.logTimeInDays", "data.loginCount", "data.managerID", "data.mobilePhoneNumber", "data.myInfo", "data.passwordDate", "data.persona", "data.phoneExtension", "data.phoneNumber", "data.portalProfileID", "data.postalCode", "data.registrationExpireDate", "data.resetPasswordExpireDate", "data.resourcePoolID", "data.roleID", "data.scheduleID", "data.scheduledDeactivationDate", "data.ssoAccessOnly", "data.ssoUsername", "data.state", "data.statusUpdate", "data.timeZone", "data.timesheetProfileID", "data.title", "data.uiTemplateID", "data.username", "data.webDAVProfile", "data.workHoursPerDay", "data.workTime", "data.parameterValues"}),
  #"Split column" = Table.SplitColumn(#"Expanded data1", "data.webDAVProfile", each _, {"data.webDAVProfile.0"}),
  #"Expanded data.parameterValues" = Table.ExpandRecordColumn(#"Split column", "data.parameterValues", {"DE:Employee Type", "DE:Creative User Role"}, {"data.parameterValues.DE:Employee Type", "data.parameterValues.DE:Creative User Role"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Expanded data.parameterValues", {{"data.ID", type text}, {"data.name", type text}, {"data.objCode", type text}, {"data.accessLevelID", type text}, {"data.actualDeactivationDate", type text}, {"data.address", type text}, {"data.avatarDate", type text}, {"data.avatarSize", Int64.Type}, {"data.avatarX", Int64.Type}, {"data.avatarY", Int64.Type}, {"data.categoryID", type text}, {"data.city", type text}, {"data.companyID", type text}, {"data.country", type text}, {"data.customerID", type text}, {"data.defaultInterface", Int64.Type}, {"data.emailAddr", type text}, {"data.enteredByID", type text}, {"data.entryDate", type text}, {"data.firstName", type text}, {"data.fte", type number}, {"data.hasAPIAccess", type logical}, {"data.hasDocuments", type logical}, {"data.hasNotes", type logical}, {"data.hasProofLicense", type logical}, {"data.hasReservedTimes", type logical}, {"data.homeGroupID", type text}, {"data.homeTeamID", type text}, {"data.isActive", type logical}, {"data.lastEnteredNoteID", type text}, {"data.lastLoginDate", type text}, {"data.lastName", type text}, {"data.lastNoteID", type text}, {"data.lastUpdateDate", type text}, {"data.lastUpdatedByID", type text}, {"data.licenseType", type text}, {"data.locale", type text}, {"data.logTimeInDays", type logical}, {"data.loginCount", Int64.Type}, {"data.managerID", type text}, {"data.mobilePhoneNumber", type text}, {"data.myInfo", type text}, {"data.passwordDate", type text}, {"data.persona", type text}, {"data.phoneExtension", type text}, {"data.phoneNumber", type text}, {"data.postalCode", Int64.Type}, {"data.registrationExpireDate", type text}, {"data.resourcePoolID", type text}, {"data.roleID", type text}, {"data.scheduleID", type text}, {"data.ssoAccessOnly", type logical}, {"data.ssoUsername", type text}, {"data.state", type text}, {"data.timeZone", type text}, {"data.timesheetProfileID", type text}, {"data.title", type text}, {"data.uiTemplateID", type text}, {"data.username", type text}, {"data.webDAVProfile.0", type text}, {"data.workHoursPerDay", Int64.Type}, {"data.workTime", Int64.Type}, {"data.parameterValues.DE:Employee Type", type text}, {"data.parameterValues.DE:Creative User Role", type text}})
in
  #"Changed column type";
