[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared Query = let
  Source = Json.Document(Web.Contents("https://teladochealth.my.workfront.com/attask/api/v19.0/hour/search?apiKey=al7s4u94ggluu08vnh7atni3p5sagebm&fields=*")),
  #"Converted to table" = Table.FromRecords({Source}),
  #"Expanded data" = Table.ExpandListColumn(#"Converted to table", "data"),
  #"Expanded data1" = Table.ExpandRecordColumn(#"Expanded data", "data", {"ID", "objCode", "actualCost", "approvedByID", "approvedOnDate", "assignedApproverID", "billingRecordID", "categoryID", "customerID", "days", "description", "dupID", "entryDate", "extRefID", "hasRateOverride", "hourTypeID", "hours", "isBillable", "lastUpdateDate", "lastUpdatedByID", "opTaskID", "ownerID", "projectID", "projectOverheadID", "rejectedByID", "rejectedOnDate", "rejectionComment", "resourceRevenue", "roleID", "securityRootID", "securityRootObjCode", "status", "submittedByID", "taskID", "timesheetHourIdentifier", "timesheetID", "workHoursPerDay"}, {"data.ID", "data.objCode", "data.actualCost", "data.approvedByID", "data.approvedOnDate", "data.assignedApproverID", "data.billingRecordID", "data.categoryID", "data.customerID", "data.days", "data.description", "data.dupID", "data.entryDate", "data.extRefID", "data.hasRateOverride", "data.hourTypeID", "data.hours", "data.isBillable", "data.lastUpdateDate", "data.lastUpdatedByID", "data.opTaskID", "data.ownerID", "data.projectID", "data.projectOverheadID", "data.rejectedByID", "data.rejectedOnDate", "data.rejectionComment", "data.resourceRevenue", "data.roleID", "data.securityRootID", "data.securityRootObjCode", "data.status", "data.submittedByID", "data.taskID", "data.timesheetHourIdentifier", "data.timesheetID", "data.workHoursPerDay"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Expanded data1", {{"data.ID", type text}, {"data.objCode", type text}, {"data.actualCost", Int64.Type}, {"data.assignedApproverID", type text}, {"data.customerID", type text}, {"data.days", type number}, {"data.description", type text}, {"data.dupID", type text}, {"data.entryDate", type date}, {"data.extRefID", type text}, {"data.hasRateOverride", type logical}, {"data.hourTypeID", type text}, {"data.hours", type number}, {"data.isBillable", type logical}, {"data.lastUpdateDate", type text}, {"data.lastUpdatedByID", type text}, {"data.ownerID", type text}, {"data.projectID", type text}, {"data.projectOverheadID", type text}, {"data.resourceRevenue", Int64.Type}, {"data.roleID", type text}, {"data.securityRootID", type text}, {"data.securityRootObjCode", type text}, {"data.status", type text}, {"data.submittedByID", type text}, {"data.taskID", type text}, {"data.timesheetHourIdentifier", type text}, {"data.timesheetID", type text}, {"data.workHoursPerDay", Int64.Type}})
in
  #"Changed column type";
