[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared Issue = let
  Source = Json.Document(Web.Contents("https://teladochealth.my.workfront.com/attask/api/v19.0/issue/search?apiKey=al7s4u94ggluu08vnh7atni3p5sagebm&method=GET&fields=*,parameterValues&projectID=679bb93a000642db193be2e527d05822")),
  #"Converted to table" = Table.FromRecords({Source}),
  #"Expanded data" = Table.ExpandListColumn(#"Converted to table", "data"),
  #"Expanded data1" = Table.ExpandRecordColumn(#"Expanded data", "data", {"ID", "name", "objCode", "actualCompletionDate", "actualCost", "actualStartDate", "actualWorkRequired", "approvalCompletionDate", "approvalProcessID", "approvalStartDate", "assignedToID", "auditTypes", "autoClosureDate", "backlogOrder", "categoryID", "color", "commitDate", "condition", "currentApprovalStepID", "customerID", "description", "enteredByID", "entryDate", "extRefID", "hasDocuments", "hasMessages", "hasNotes", "hasResolvables", "hasTimedNotifications", "isComplete", "isHelpDesk", "isReady", "iterationID", "kanbanBoardID", "lastConditionNoteID", "lastNoteID", "lastUpdateDate", "lastUpdatedByID", "opTaskType", "ownerID", "percentComplete", "plannedCompletionDate", "plannedDurationMinutes", "plannedStartDate", "previousStatus", "priority", "projectID", "projectedDurationMinutes", "queueTopicID", "referenceNumber", "remainingDurationMinutes", "resolveOpTaskID", "resolveProjectID", "resolveTaskID", "resolvingObjCode", "resolvingObjID", "roleID", "securityRootID", "securityRootObjCode", "severity", "sourceObjCode", "sourceObjID", "sourceTaskID", "status", "statusUpdate", "storyBoardOrder", "storyPoints", "submittedByID", "teamID", "url", "version", "work", "workRequired", "parameterValues"}, {"data.ID", "data.name", "data.objCode", "data.actualCompletionDate", "data.actualCost", "data.actualStartDate", "data.actualWorkRequired", "data.approvalCompletionDate", "data.approvalProcessID", "data.approvalStartDate", "data.assignedToID", "data.auditTypes", "data.autoClosureDate", "data.backlogOrder", "data.categoryID", "data.color", "data.commitDate", "data.condition", "data.currentApprovalStepID", "data.customerID", "data.description", "data.enteredByID", "data.entryDate", "data.extRefID", "data.hasDocuments", "data.hasMessages", "data.hasNotes", "data.hasResolvables", "data.hasTimedNotifications", "data.isComplete", "data.isHelpDesk", "data.isReady", "data.iterationID", "data.kanbanBoardID", "data.lastConditionNoteID", "data.lastNoteID", "data.lastUpdateDate", "data.lastUpdatedByID", "data.opTaskType", "data.ownerID", "data.percentComplete", "data.plannedCompletionDate", "data.plannedDurationMinutes", "data.plannedStartDate", "data.previousStatus", "data.priority", "data.projectID", "data.projectedDurationMinutes", "data.queueTopicID", "data.referenceNumber", "data.remainingDurationMinutes", "data.resolveOpTaskID", "data.resolveProjectID", "data.resolveTaskID", "data.resolvingObjCode", "data.resolvingObjID", "data.roleID", "data.securityRootID", "data.securityRootObjCode", "data.severity", "data.sourceObjCode", "data.sourceObjID", "data.sourceTaskID", "data.status", "data.statusUpdate", "data.storyBoardOrder", "data.storyPoints", "data.submittedByID", "data.teamID", "data.url", "data.version", "data.work", "data.workRequired", "data.parameterValues"}),
  #"Expanded data.parameterValues" = Table.ExpandRecordColumn(#"Expanded data1", "data.parameterValues", {"DE:OG-Root Cause Analysis Status", "DE:OG-Contributors2", "DE:OG-Solution Hypothesis", "DE:Bussiness Strategy Priorities", "DE:Og-Comments", "DE:OG-Additional Information", "DE:OG-Bussiness Requirements Document Status", "DE:Budget Status", "DE:Project Status", "DE:OG-Training", "DE:Risk/Impact if something brokes", "DE:OG-Project Owner", "DE:Og-Expected Timeline", "DE:OG-Approval Person/Team", "DE:OG-Documentation & Communication", "DE:OG-Measure  Stage Status", "DE:OG-Project ID", "DE:OG-Solution Architect", "DE:OG-Impacted if no solution is implemented", "DE:OG-KPI ID", "DE:OG-Adittional Information/Attachements", "DE:OG-Project Name", "DE:OG-Client Specific Impact", "DE:OG-Products", "DE:OG-Conclusions", "DE:OG-Define Status", "DE:OG-Impacted Systems", "DE:OG-Progress Update", "DE:OG-Funding Selection", "DE:OG-Estimated Project Complexity", "DE:OG-Estimated Project Duration", "DE:Project Owner", "DE:OG-Root Cause Analysis RCA", "DE:OG-Executive Sponsor", "DE:OG-Bussiness Continuity Plan", "DE:OG-LOE Monthly/Weekly", "DE:OG-Project Effective End/Close Date", "DE:OG-Reporting Dashboards & Metrics", "DE:OG-Related KPI2", "DE:What Does Success like?", "DE:OG-Root Cause Hypothesis2", "DE:OG-Bussiness Objective/s", "DE:OG-ROI - Return Of Investment", "DE:OG-Actual Outcomes"}, {"data.parameterValues.DE:OG-Root Cause Analysis Status", "data.parameterValues.DE:OG-Contributors2", "data.parameterValues.DE:OG-Solution Hypothesis", "data.parameterValues.DE:Bussiness Strategy Priorities", "data.parameterValues.DE:Og-Comments", "data.parameterValues.DE:OG-Additional Information", "data.parameterValues.DE:OG-Bussiness Requirements Document Status", "data.parameterValues.DE:Budget Status", "data.parameterValues.DE:Project Status", "data.parameterValues.DE:OG-Training", "data.parameterValues.DE:Risk/Impact if something brokes", "data.parameterValues.DE:OG-Project Owner", "data.parameterValues.DE:Og-Expected Timeline", "data.parameterValues.DE:OG-Approval Person/Team", "data.parameterValues.DE:OG-Documentation & Communication", "data.parameterValues.DE:OG-Measure  Stage Status", "data.parameterValues.DE:OG-Project ID", "data.parameterValues.DE:OG-Solution Architect", "data.parameterValues.DE:OG-Impacted if no solution is implemented", "data.parameterValues.DE:OG-KPI ID", "data.parameterValues.DE:OG-Adittional Information/Attachements", "data.parameterValues.DE:OG-Project Name", "data.parameterValues.DE:OG-Client Specific Impact", "data.parameterValues.DE:OG-Products", "data.parameterValues.DE:OG-Conclusions", "data.parameterValues.DE:OG-Define Status", "data.parameterValues.DE:OG-Impacted Systems", "data.parameterValues.DE:OG-Progress Update", "data.parameterValues.DE:OG-Funding Selection", "data.parameterValues.DE:OG-Estimated Project Complexity", "data.parameterValues.DE:OG-Estimated Project Duration", "data.parameterValues.DE:Project Owner", "data.parameterValues.DE:OG-Root Cause Analysis RCA", "data.parameterValues.DE:OG-Executive Sponsor", "data.parameterValues.DE:OG-Bussiness Continuity Plan", "data.parameterValues.DE:OG-LOE Monthly/Weekly", "data.parameterValues.DE:OG-Project Effective End/Close Date", "data.parameterValues.DE:OG-Reporting Dashboards & Metrics", "data.parameterValues.DE:OG-Related KPI2", "data.parameterValues.DE:What Does Success like?", "data.parameterValues.DE:OG-Root Cause Hypothesis2", "data.parameterValues.DE:OG-Bussiness Objective/s", "data.parameterValues.DE:OG-ROI - Return Of Investment", "data.parameterValues.DE:OG-Actual Outcomes"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Expanded data.parameterValues", {{"data.ID", type text}, {"data.name", type text}, {"data.objCode", type text}, {"data.actualCompletionDate", type text}, {"data.actualCost", Int64.Type}, {"data.actualStartDate", type text}, {"data.actualWorkRequired", Int64.Type}, {"data.assignedToID", type text}, {"data.autoClosureDate", type text}, {"data.backlogOrder", Int64.Type}, {"data.categoryID", type text}, {"data.commitDate", type text}, {"data.condition", Int64.Type}, {"data.customerID", type text}, {"data.description", type text}, {"data.enteredByID", type text}, {"data.entryDate", type text}, {"data.hasDocuments", type logical}, {"data.hasMessages", type logical}, {"data.hasNotes", type logical}, {"data.hasResolvables", type logical}, {"data.hasTimedNotifications", type logical}, {"data.isComplete", type logical}, {"data.isHelpDesk", type logical}, {"data.isReady", type logical}, {"data.lastUpdateDate", type text}, {"data.lastUpdatedByID", type text}, {"data.opTaskType", type text}, {"data.ownerID", type text}, {"data.percentComplete", Int64.Type}, {"data.plannedCompletionDate", type text}, {"data.plannedDurationMinutes", Int64.Type}, {"data.plannedStartDate", type text}, {"data.previousStatus", type text}, {"data.priority", Int64.Type}, {"data.projectID", type text}, {"data.projectedDurationMinutes", Int64.Type}, {"data.referenceNumber", Int64.Type}, {"data.remainingDurationMinutes", Int64.Type}, {"data.roleID", type text}, {"data.securityRootID", type text}, {"data.securityRootObjCode", type text}, {"data.severity", Int64.Type}, {"data.status", type text}, {"data.storyBoardOrder", Int64.Type}, {"data.storyPoints", Int64.Type}, {"data.url", type text}, {"data.version", Int64.Type}, {"data.work", Int64.Type}, {"data.workRequired", Int64.Type}, {"data.parameterValues.DE:OG-Root Cause Analysis Status", type text}, {"data.parameterValues.DE:OG-Contributors2", type text}, {"data.parameterValues.DE:OG-Solution Hypothesis", type text}, {"data.parameterValues.DE:Bussiness Strategy Priorities", type text}, {"data.parameterValues.DE:Og-Comments", type text}, {"data.parameterValues.DE:OG-Additional Information", type text}, {"data.parameterValues.DE:OG-Bussiness Requirements Document Status", type text}, {"data.parameterValues.DE:Budget Status", type text}, {"data.parameterValues.DE:Project Status", type text}, {"data.parameterValues.DE:OG-Training", type text}, {"data.parameterValues.DE:Risk/Impact if something brokes", type text}, {"data.parameterValues.DE:OG-Project Owner", type text}, {"data.parameterValues.DE:Og-Expected Timeline", type date}, {"data.parameterValues.DE:OG-Approval Person/Team", type text}, {"data.parameterValues.DE:OG-Documentation & Communication", type text}, {"data.parameterValues.DE:OG-Measure  Stage Status", type text}, {"data.parameterValues.DE:OG-Project ID", Int64.Type}, {"data.parameterValues.DE:OG-Solution Architect", type text}, {"data.parameterValues.DE:OG-Impacted if no solution is implemented", type text}, {"data.parameterValues.DE:OG-KPI ID", type text}, {"data.parameterValues.DE:OG-Adittional Information/Attachements", type text}, {"data.parameterValues.DE:OG-Project Name", type text}, {"data.parameterValues.DE:OG-Client Specific Impact", type text}, {"data.parameterValues.DE:OG-Conclusions", type text}, {"data.parameterValues.DE:OG-Define Status", type text}, {"data.parameterValues.DE:OG-Progress Update", type text}, {"data.parameterValues.DE:OG-Funding Selection", type text}, {"data.parameterValues.DE:OG-Estimated Project Complexity", type text}, {"data.parameterValues.DE:OG-Estimated Project Duration", type text}, {"data.parameterValues.DE:Project Owner", type text}, {"data.parameterValues.DE:OG-Root Cause Analysis RCA", type text}, {"data.parameterValues.DE:OG-Executive Sponsor", type text}, {"data.parameterValues.DE:OG-Bussiness Continuity Plan", type text}, {"data.parameterValues.DE:OG-LOE Monthly/Weekly", type text}, {"data.parameterValues.DE:OG-Project Effective End/Close Date", type date}, {"data.parameterValues.DE:OG-Reporting Dashboards & Metrics", type text}, {"data.parameterValues.DE:OG-Related KPI2", type text}, {"data.parameterValues.DE:What Does Success like?", type text}, {"data.parameterValues.DE:OG-Root Cause Hypothesis2", type text}, {"data.parameterValues.DE:OG-Bussiness Objective/s", type text}, {"data.parameterValues.DE:OG-ROI - Return Of Investment", type text}, {"data.parameterValues.DE:OG-Actual Outcomes", type text}})
in
  #"Changed column type";
