[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared Query = let
  Source = Json.Document(Web.Contents("https://teladochealth.my.workfront.com/attask/api/v19.0/issue/search?apiKey=al7s4u94ggluu08vnh7atni3p5sagebm&fields=*,parameterValues")),
  #"Converted to table" = Table.FromRecords({Source}),
  #"Expanded data" = Table.ExpandListColumn(#"Converted to table", "data"),
  #"Expanded data1" = Table.ExpandRecordColumn(#"Expanded data", "data", {"ID", "name", "objCode", "actualCompletionDate", "actualCost", "actualStartDate", "actualWorkRequired", "approvalCompletionDate", "approvalProcessID", "approvalStartDate", "assignedToID", "auditTypes", "autoClosureDate", "backlogOrder", "categoryID", "color", "commitDate", "condition", "currentApprovalStepID", "customerID", "description", "enteredByID", "entryDate", "extRefID", "hasDocuments", "hasMessages", "hasNotes", "hasResolvables", "hasTimedNotifications", "isComplete", "isHelpDesk", "isReady", "iterationID", "kanbanBoardID", "lastConditionNoteID", "lastNoteID", "lastUpdateDate", "lastUpdatedByID", "opTaskType", "ownerID", "percentComplete", "plannedCompletionDate", "plannedDurationMinutes", "plannedStartDate", "previousStatus", "priority", "projectID", "projectedDurationMinutes", "queueTopicID", "referenceNumber", "remainingDurationMinutes", "resolveOpTaskID", "resolveProjectID", "resolveTaskID", "resolvingObjCode", "resolvingObjID", "roleID", "securityRootID", "securityRootObjCode", "severity", "sourceObjCode", "sourceObjID", "sourceTaskID", "status", "statusUpdate", "storyBoardOrder", "storyPoints", "submittedByID", "teamID", "url", "version", "work", "workRequired", "parameterValues"}, {"data.ID", "data.name", "data.objCode", "data.actualCompletionDate", "data.actualCost", "data.actualStartDate", "data.actualWorkRequired", "data.approvalCompletionDate", "data.approvalProcessID", "data.approvalStartDate", "data.assignedToID", "data.auditTypes", "data.autoClosureDate", "data.backlogOrder", "data.categoryID", "data.color", "data.commitDate", "data.condition", "data.currentApprovalStepID", "data.customerID", "data.description", "data.enteredByID", "data.entryDate", "data.extRefID", "data.hasDocuments", "data.hasMessages", "data.hasNotes", "data.hasResolvables", "data.hasTimedNotifications", "data.isComplete", "data.isHelpDesk", "data.isReady", "data.iterationID", "data.kanbanBoardID", "data.lastConditionNoteID", "data.lastNoteID", "data.lastUpdateDate", "data.lastUpdatedByID", "data.opTaskType", "data.ownerID", "data.percentComplete", "data.plannedCompletionDate", "data.plannedDurationMinutes", "data.plannedStartDate", "data.previousStatus", "data.priority", "data.projectID", "data.projectedDurationMinutes", "data.queueTopicID", "data.referenceNumber", "data.remainingDurationMinutes", "data.resolveOpTaskID", "data.resolveProjectID", "data.resolveTaskID", "data.resolvingObjCode", "data.resolvingObjID", "data.roleID", "data.securityRootID", "data.securityRootObjCode", "data.severity", "data.sourceObjCode", "data.sourceObjID", "data.sourceTaskID", "data.status", "data.statusUpdate", "data.storyBoardOrder", "data.storyPoints", "data.submittedByID", "data.teamID", "data.url", "data.version", "data.work", "data.workRequired", "data.parameterValues"}),
  #"Expanded data.parameterValues" = Table.ExpandRecordColumn(#"Expanded data1", "data.parameterValues", {"DE:BT - Regulatory Score", "DE:Ready to be Evaluated?", "DE:BT - Number of Systems Impacted", "DE:BT - Total Systems", "DE:BT - OKR 1 Score", "DE:BT - What Work If Any Has Been Completed to Date?", "DE:BT - Systems Impacted Score", "DE:BT - Business Continuity Score", "DE:BT - Total Benefit Score", "DE:Which channels will this ad appear in?", "DE:Will  you need copy to go with this asset?", "DE:Channel Deliverable - Display", "DE:Channel Deliverables - LinkedIn", "DE:If other, please note below", "DE:BT - Team Name", "DE:Who will be impacted by this project?", "DE:What areas may be impacted by this project?", "DE:BT - Project Executive Sponsor - SVP/ELT Level", "DE:BT - Level of Change Score", "DE:BT - Region", "DE:BT - Background and Current State Challenges", "DE:BT - OKR 4 Score", "DE:BT - Total Score", "DE:BT - Total Complexity Score", "DE:BT - Area of Business", "DE:BT - Is this request confidential?", "DE:BT - Timeline/Urgency", "DE:BT - Project Type", "DE:BT - Project Team's experience Score", "DE:BT - OKR 2 Score", "DE:BT - Urgency Score", "DE:BT - OKR 3 Score", "DE:BT - Number of Other Systems", "DE:BT - Number of Teams Score", "DE:BT - Project Prioritization Recommendation", "DE:BT - OKR 5 Score", "DE:BT - Duration Score", "DE:BT - Business Impact Score", "DE:BT - Project Sponsor - Director/VP Level", "DE:BT - Cost Score", "DE:Brand", "DE:Is this Landing Page using an existing template?", "DE:Will speakers be highlighted on this landing page?", "DE:If yes, provide asset or job number or description", "DE:Asset size", "DE:Will this route to Propel for legal review?", "DE:Will your project need a creative strategist?", "DE:Where will files be delivered?", "DE:Project Notes", "DE:Will this piece require translations?", "DE:Please provide # of rounds and # of days per round for client reviews", "DE:If other or notes are needed please provide below", "DE:If other collateral asset type, please note here", "DE:Is there an existing Workfront project?", "DE:What makes up the cultural and market context?", "DE:If change to existing video provide link to the video", "DE:Provide creative thought starters", "DE:Project notes", "DE:If video is net new, please provide style direction or example of styles you like", "DE:What devices will this video highlight?", "DE:How can we support this?", "DE:DM asset type", "DE:Description of changes needed", "DE:Projected Launch Date", "DE:Will this piece need to be AODA compliant?", "DE:What day does your Landing Page need to go live?", "DE:The Ask", "DE:What type of social ad is this?", "DE:What does success look like?", "DE:If other, please provide channel information", "DE:Provide where final video will live", "DE:Planned Duration", "DE:What day does your email need to deploy?", "DE:Channel Deliverables - Meta - FB + Instagram", "DE:Channel Deliverables - Twitter", "DE:Is video net new?", "DE:Are you linking to a Teladoc Health Web page or landing page?", "DE:What is the most important insight about the customer?", "DE:Please Select Line of Business", "DE:If other, provide notes below", "DE:Are we using an existing approved format?", "DE:If yes, outline your testing request below; or upload your test hypothesis at the end of this brief", "DE:If 2+ versions are chosen, please upload a version matrix at the end of this brief", "DE:Provide any related assets at the end of this brief", "DE:Where will this video be used?", "DE:Provide official video title", "DE:Will blog live on Teladoc.com HealthTalk?", "DE:Channel Deliverables - Banner", "DE:What size is your asset?", "DE:which template will we use?", "DE:Has your executive sponsor reviewed and approved this brief?", "DE:B2B - Which Services will this project feature?", "DE:Is this piece being created for a client?", "DE:How will the final assets be delivered?", "DE:Are interviews required for this blog?", "DE:How will contact list be built?", "DE:Provide file format for asset delivery", "DE:New Asset Type", "DE:Will testing be requested on this project?", "DE:Related Project", "DE:Chose your collateral asset type", "DE:Requested due date", "DE:Are any marketing materials driving to this blog?", "DE:Which Services will this project feature?", "DE:If other is chosen, provide file specifications below", "DE:What is your billing code?", "DE:Which PPT template will be used as the base?", "DE:Who will be approving the SOW?", "DE:CM- Where will files be delivered?", "DE:If routing to Propel, please provide PM codes here", "DE:Please provide existing Landing page  URL", "DE:Estimated length of requested video", "DE:Does this video have a budget?", "DE:Provide privacy settings on Vimeo/Other", "DE:What is the most important thing we want our audience to take away?", "DE:Provide the name of the client", "DE:if content is provided, by whom and when will it be delivered?", "DE:Tracking requirements", "DE:Will this piece need to route to an external client for review?", "DE:Provide the CTA for the video", "DE:Are external sources needed to support creative development?", "DE:What are the core campaign elements?", "DE:UTM code for any asset that links to a TDH webpage.", "DE:How many versions of this piece will be delivered?", "DE:What enhancements/work do you want done?", "DE:Your requested due date", "DE:Line of Business", "DE:List of people to add to your proof as a reviewer", "DE:Executive Sponsor", "DE:On which system will the content asset be stored?", "DE:Has your executive sponsor approved this request?", "DE:Provide any overall information the creative team may need to execute", "DE:Will any content be provided?"}, {"data.parameterValues.DE:BT - Regulatory Score", "data.parameterValues.DE:Ready to be Evaluated?", "data.parameterValues.DE:BT - Number of Systems Impacted", "data.parameterValues.DE:BT - Total Systems", "data.parameterValues.DE:BT - OKR 1 Score", "data.parameterValues.DE:BT - What Work If Any Has Been Completed to Date?", "data.parameterValues.DE:BT - Systems Impacted Score", "data.parameterValues.DE:BT - Business Continuity Score", "data.parameterValues.DE:BT - Total Benefit Score", "data.parameterValues.DE:Which channels will this ad appear in?", "data.parameterValues.DE:Will  you need copy to go with this asset?", "data.parameterValues.DE:Channel Deliverable - Display", "data.parameterValues.DE:Channel Deliverables - LinkedIn", "data.parameterValues.DE:If other, please note below", "data.parameterValues.DE:BT - Team Name", "data.parameterValues.DE:Who will be impacted by this project?", "data.parameterValues.DE:What areas may be impacted by this project?", "data.parameterValues.DE:BT - Project Executive Sponsor - SVP/ELT Level", "data.parameterValues.DE:BT - Level of Change Score", "data.parameterValues.DE:BT - Region", "data.parameterValues.DE:BT - Background and Current State Challenges", "data.parameterValues.DE:BT - OKR 4 Score", "data.parameterValues.DE:BT - Total Score", "data.parameterValues.DE:BT - Total Complexity Score", "data.parameterValues.DE:BT - Area of Business", "data.parameterValues.DE:BT - Is this request confidential?", "data.parameterValues.DE:BT - Timeline/Urgency", "data.parameterValues.DE:BT - Project Type", "data.parameterValues.DE:BT - Project Team's experience Score", "data.parameterValues.DE:BT - OKR 2 Score", "data.parameterValues.DE:BT - Urgency Score", "data.parameterValues.DE:BT - OKR 3 Score", "data.parameterValues.DE:BT - Number of Other Systems", "data.parameterValues.DE:BT - Number of Teams Score", "data.parameterValues.DE:BT - Project Prioritization Recommendation", "data.parameterValues.DE:BT - OKR 5 Score", "data.parameterValues.DE:BT - Duration Score", "data.parameterValues.DE:BT - Business Impact Score", "data.parameterValues.DE:BT - Project Sponsor - Director/VP Level", "data.parameterValues.DE:BT - Cost Score", "data.parameterValues.DE:Brand", "data.parameterValues.DE:Is this Landing Page using an existing template?", "data.parameterValues.DE:Will speakers be highlighted on this landing page?", "data.parameterValues.DE:If yes, provide asset or job number or description", "data.parameterValues.DE:Asset size", "data.parameterValues.DE:Will this route to Propel for legal review?", "data.parameterValues.DE:Will your project need a creative strategist?", "data.parameterValues.DE:Where will files be delivered?", "data.parameterValues.DE:Project Notes", "data.parameterValues.DE:Will this piece require translations?", "data.parameterValues.DE:Please provide # of rounds and # of days per round for client reviews", "data.parameterValues.DE:If other or notes are needed please provide below", "data.parameterValues.DE:If other collateral asset type, please note here", "data.parameterValues.DE:Is there an existing Workfront project?", "data.parameterValues.DE:What makes up the cultural and market context?", "data.parameterValues.DE:If change to existing video provide link to the video", "data.parameterValues.DE:Provide creative thought starters", "data.parameterValues.DE:Project notes", "data.parameterValues.DE:If video is net new, please provide style direction or example of styles you like", "data.parameterValues.DE:What devices will this video highlight?", "data.parameterValues.DE:How can we support this?", "data.parameterValues.DE:DM asset type", "data.parameterValues.DE:Description of changes needed", "data.parameterValues.DE:Projected Launch Date", "data.parameterValues.DE:Will this piece need to be AODA compliant?", "data.parameterValues.DE:What day does your Landing Page need to go live?", "data.parameterValues.DE:The Ask", "data.parameterValues.DE:What type of social ad is this?", "data.parameterValues.DE:What does success look like?", "data.parameterValues.DE:If other, please provide channel information", "data.parameterValues.DE:Provide where final video will live", "data.parameterValues.DE:Planned Duration", "data.parameterValues.DE:What day does your email need to deploy?", "data.parameterValues.DE:Channel Deliverables - Meta - FB + Instagram", "data.parameterValues.DE:Channel Deliverables - Twitter", "data.parameterValues.DE:Is video net new?", "data.parameterValues.DE:Are you linking to a Teladoc Health Web page or landing page?", "data.parameterValues.DE:What is the most important insight about the customer?", "data.parameterValues.DE:Please Select Line of Business", "data.parameterValues.DE:If other, provide notes below", "data.parameterValues.DE:Are we using an existing approved format?", "data.parameterValues.DE:If yes, outline your testing request below; or upload your test hypothesis at the end of this brief", "data.parameterValues.DE:If 2+ versions are chosen, please upload a version matrix at the end of this brief", "data.parameterValues.DE:Provide any related assets at the end of this brief", "data.parameterValues.DE:Where will this video be used?", "data.parameterValues.DE:Provide official video title", "data.parameterValues.DE:Will blog live on Teladoc.com HealthTalk?", "data.parameterValues.DE:Channel Deliverables - Banner", "data.parameterValues.DE:What size is your asset?", "data.parameterValues.DE:which template will we use?", "data.parameterValues.DE:Has your executive sponsor reviewed and approved this brief?", "data.parameterValues.DE:B2B - Which Services will this project feature?", "data.parameterValues.DE:Is this piece being created for a client?", "data.parameterValues.DE:How will the final assets be delivered?", "data.parameterValues.DE:Are interviews required for this blog?", "data.parameterValues.DE:How will contact list be built?", "data.parameterValues.DE:Provide file format for asset delivery", "data.parameterValues.DE:New Asset Type", "data.parameterValues.DE:Will testing be requested on this project?", "data.parameterValues.DE:Related Project", "data.parameterValues.DE:Chose your collateral asset type", "data.parameterValues.DE:Requested due date", "data.parameterValues.DE:Are any marketing materials driving to this blog?", "data.parameterValues.DE:Which Services will this project feature?", "data.parameterValues.DE:If other is chosen, provide file specifications below", "data.parameterValues.DE:What is your billing code?", "data.parameterValues.DE:Which PPT template will be used as the base?", "data.parameterValues.DE:Who will be approving the SOW?", "data.parameterValues.DE:CM- Where will files be delivered?", "data.parameterValues.DE:If routing to Propel, please provide PM codes here", "data.parameterValues.DE:Please provide existing Landing page  URL", "data.parameterValues.DE:Estimated length of requested video", "data.parameterValues.DE:Does this video have a budget?", "data.parameterValues.DE:Provide privacy settings on Vimeo/Other", "data.parameterValues.DE:What is the most important thing we want our audience to take away?", "data.parameterValues.DE:Provide the name of the client", "data.parameterValues.DE:if content is provided, by whom and when will it be delivered?", "data.parameterValues.DE:Tracking requirements", "data.parameterValues.DE:Will this piece need to route to an external client for review?", "data.parameterValues.DE:Provide the CTA for the video", "data.parameterValues.DE:Are external sources needed to support creative development?", "data.parameterValues.DE:What are the core campaign elements?", "data.parameterValues.DE:UTM code for any asset that links to a TDH webpage.", "data.parameterValues.DE:How many versions of this piece will be delivered?", "data.parameterValues.DE:What enhancements/work do you want done?", "data.parameterValues.DE:Your requested due date", "data.parameterValues.DE:Line of Business", "data.parameterValues.DE:List of people to add to your proof as a reviewer", "data.parameterValues.DE:Executive Sponsor", "data.parameterValues.DE:On which system will the content asset be stored?", "data.parameterValues.DE:Has your executive sponsor approved this request?", "data.parameterValues.DE:Provide any overall information the creative team may need to execute", "data.parameterValues.DE:Will any content be provided?"}),
  #"Split column" = Table.SplitColumn(#"Expanded data.parameterValues", "data.parameterValues.DE:What are the core campaign elements?", each _, {"data.parameterValues.DE:What are the core campaign elements?.0", "data.parameterValues.DE:What are the core campaign elements?.1"})
in
  #"Split column";
