[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared Query = let
  Source = Json.Document(Web.Contents("https://teladochealth.my.workfront.com/attask/api/v19.0/task/search?apiKey=al7s4u94ggluu08vnh7atni3p5sagebm&fields=*,parameterValues")),
  #"Converted to table" = Table.FromRecords({Source}),
  #"Expanded data" = Table.ExpandListColumn(#"Converted to table", "data"),
  #"Expanded data1" = Table.ExpandRecordColumn(#"Expanded data", "data", {"ID", "name", "objCode", "URL", "actualBillableExpenseCost", "actualCompletionDate", "actualCost", "actualDuration", "actualDurationMinutes", "actualExpenseCost", "actualLaborCost", "actualNonBillableExpenseCost", "actualRevenue", "actualStartDate", "actualWork", "actualWorkRequired", "approvalCompletionDate", "approvalEstStartDate", "approvalPlannedStartDate", "approvalProcessID", "approvalProjectedStartDate", "approvalStartDate", "assignedToID", "auditTypes", "backlogOrder", "bcwp", "bcws", "billingAmount", "billingRecordID", "canStart", "categoryID", "color", "commitDate", "completionPendingDate", "condition", "constraintDate", "convertedOpTaskEntryDate", "convertedOpTaskName", "convertedOpTaskOriginatorID", "costAmount", "costType", "cpi", "csi", "currentApprovalStepID", "customerID", "description", "duration", "durationMinutes", "durationType", "durationUnit", "eac", "enteredByID", "entryDate", "estCompletionDate", "estStartDate", "extRefID", "groupID", "handoffDate", "hasCompletionConstraint", "hasDocuments", "hasExpenses", "hasMessages", "hasNotes", "hasResolvables", "hasStartConstraint", "hasTimedNotifications", "hoursPerPoint", "indent", "isAgile", "isCritical", "isDurationLocked", "isLevelingExcluded", "isReady", "isStatusComplete", "isWorkRequiredLocked", "iterationID", "kanbanBoardID", "kanbanFlag", "lastConditionNoteID", "lastNoteID", "lastUpdateDate", "lastUpdatedByID", "levelingStartDelay", "levelingStartDelayMinutes", "milestoneID", "numberOfChildren", "numberOpenOpTasks", "originalDuration", "originalWorkRequired", "parentID", "parentLag", "parentLagType", "pendingCalculation", "pendingUpdateMethods", "percentComplete", "personal", "plannedBillableExpenseCost", "plannedCompletionDate", "plannedCost", "plannedDuration", "plannedDurationMinutes", "plannedExpenseCost", "plannedLaborCost", "plannedNonBillableExpenseCost", "plannedRevenue", "plannedStartDate", "previousStatus", "priority", "progressStatus", "projectID", "projectedCompletionDate", "projectedDurationMinutes", "projectedStartDate", "recurrenceNumber", "recurrenceRuleID", "referenceNumber", "rejectionIssueID", "remainingDurationMinutes", "resourceScope", "revenueType", "roleID", "securityRootID", "securityRootObjCode", "slackDate", "spi", "status", "statusUpdate", "storyPoints", "submittedByID", "taskConstraint", "taskNumber", "teamID", "templateTaskID", "trackingMode", "version", "wbs", "work", "workEffort", "workRequired", "parameterValues"}, {"data.ID", "data.name", "data.objCode", "data.URL", "data.actualBillableExpenseCost", "data.actualCompletionDate", "data.actualCost", "data.actualDuration", "data.actualDurationMinutes", "data.actualExpenseCost", "data.actualLaborCost", "data.actualNonBillableExpenseCost", "data.actualRevenue", "data.actualStartDate", "data.actualWork", "data.actualWorkRequired", "data.approvalCompletionDate", "data.approvalEstStartDate", "data.approvalPlannedStartDate", "data.approvalProcessID", "data.approvalProjectedStartDate", "data.approvalStartDate", "data.assignedToID", "data.auditTypes", "data.backlogOrder", "data.bcwp", "data.bcws", "data.billingAmount", "data.billingRecordID", "data.canStart", "data.categoryID", "data.color", "data.commitDate", "data.completionPendingDate", "data.condition", "data.constraintDate", "data.convertedOpTaskEntryDate", "data.convertedOpTaskName", "data.convertedOpTaskOriginatorID", "data.costAmount", "data.costType", "data.cpi", "data.csi", "data.currentApprovalStepID", "data.customerID", "data.description", "data.duration", "data.durationMinutes", "data.durationType", "data.durationUnit", "data.eac", "data.enteredByID", "data.entryDate", "data.estCompletionDate", "data.estStartDate", "data.extRefID", "data.groupID", "data.handoffDate", "data.hasCompletionConstraint", "data.hasDocuments", "data.hasExpenses", "data.hasMessages", "data.hasNotes", "data.hasResolvables", "data.hasStartConstraint", "data.hasTimedNotifications", "data.hoursPerPoint", "data.indent", "data.isAgile", "data.isCritical", "data.isDurationLocked", "data.isLevelingExcluded", "data.isReady", "data.isStatusComplete", "data.isWorkRequiredLocked", "data.iterationID", "data.kanbanBoardID", "data.kanbanFlag", "data.lastConditionNoteID", "data.lastNoteID", "data.lastUpdateDate", "data.lastUpdatedByID", "data.levelingStartDelay", "data.levelingStartDelayMinutes", "data.milestoneID", "data.numberOfChildren", "data.numberOpenOpTasks", "data.originalDuration", "data.originalWorkRequired", "data.parentID", "data.parentLag", "data.parentLagType", "data.pendingCalculation", "data.pendingUpdateMethods", "data.percentComplete", "data.personal", "data.plannedBillableExpenseCost", "data.plannedCompletionDate", "data.plannedCost", "data.plannedDuration", "data.plannedDurationMinutes", "data.plannedExpenseCost", "data.plannedLaborCost", "data.plannedNonBillableExpenseCost", "data.plannedRevenue", "data.plannedStartDate", "data.previousStatus", "data.priority", "data.progressStatus", "data.projectID", "data.projectedCompletionDate", "data.projectedDurationMinutes", "data.projectedStartDate", "data.recurrenceNumber", "data.recurrenceRuleID", "data.referenceNumber", "data.rejectionIssueID", "data.remainingDurationMinutes", "data.resourceScope", "data.revenueType", "data.roleID", "data.securityRootID", "data.securityRootObjCode", "data.slackDate", "data.spi", "data.status", "data.statusUpdate", "data.storyPoints", "data.submittedByID", "data.taskConstraint", "data.taskNumber", "data.teamID", "data.templateTaskID", "data.trackingMode", "data.version", "data.wbs", "data.work", "data.workEffort", "data.workRequired", "data.parameterValues"}),
  #"Expanded data.parameterValues" = Table.ExpandRecordColumn(#"Expanded data1", "data.parameterValues", {"DE:Change Timeline", "DE:Client Facing", "DE:On Time Status", "DE:Current Due Date", "DE:Planned Completion No Time", "DE:Partner Contract Path", "DE:Disqualifiers & Concerns", "DE:Client Eligibility Type", "DE:Client Manager", "DE:Migration Category at Migration", "DE:TPM Lead", "DE:Client or Access Code", "DE:Invited to Migrate", "DE:Client Agreed For Migration", "DE:Migration Category", "DE:MyS Guage Count As", "DE:Date Preference For Migration"}, {"data.parameterValues.DE:Change Timeline", "data.parameterValues.DE:Client Facing", "data.parameterValues.DE:On Time Status", "data.parameterValues.DE:Current Due Date", "data.parameterValues.DE:Planned Completion No Time", "data.parameterValues.DE:Partner Contract Path", "data.parameterValues.DE:Disqualifiers & Concerns", "data.parameterValues.DE:Client Eligibility Type", "data.parameterValues.DE:Client Manager", "data.parameterValues.DE:Migration Category at Migration", "data.parameterValues.DE:TPM Lead", "data.parameterValues.DE:Client or Access Code", "data.parameterValues.DE:Invited to Migrate", "data.parameterValues.DE:Client Agreed For Migration", "data.parameterValues.DE:Migration Category", "data.parameterValues.DE:MyS Guage Count As", "data.parameterValues.DE:Date Preference For Migration"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Expanded data.parameterValues", {{"data.ID", type text}, {"data.name", type text}, {"data.objCode", type text}, {"data.URL", type text}, {"data.actualBillableExpenseCost", Int64.Type}, {"data.actualCost", Int64.Type}, {"data.actualDuration", Int64.Type}, {"data.actualDurationMinutes", Int64.Type}, {"data.actualExpenseCost", Int64.Type}, {"data.actualLaborCost", Int64.Type}, {"data.actualNonBillableExpenseCost", Int64.Type}, {"data.actualRevenue", Int64.Type}, {"data.actualStartDate", type text}, {"data.actualWork", type number}, {"data.actualWorkRequired", Int64.Type}, {"data.assignedToID", type text}, {"data.backlogOrder", Int64.Type}, {"data.bcwp", Int64.Type}, {"data.bcws", type number}, {"data.billingAmount", Int64.Type}, {"data.canStart", type logical}, {"data.categoryID", type text}, {"data.commitDate", type text}, {"data.condition", Int64.Type}, {"data.constraintDate", type text}, {"data.costAmount", Int64.Type}, {"data.costType", type text}, {"data.cpi", Int64.Type}, {"data.csi", Int64.Type}, {"data.customerID", type text}, {"data.description", type text}, {"data.duration", Int64.Type}, {"data.durationMinutes", Int64.Type}, {"data.durationType", type text}, {"data.durationUnit", type text}, {"data.eac", type number}, {"data.enteredByID", type text}, {"data.entryDate", type text}, {"data.estCompletionDate", type text}, {"data.estStartDate", type text}, {"data.extRefID", type text}, {"data.groupID", type text}, {"data.handoffDate", type text}, {"data.hasCompletionConstraint", type logical}, {"data.hasDocuments", type logical}, {"data.hasExpenses", type logical}, {"data.hasMessages", type logical}, {"data.hasNotes", type logical}, {"data.hasResolvables", type logical}, {"data.hasStartConstraint", type logical}, {"data.hasTimedNotifications", type logical}, {"data.hoursPerPoint", Int64.Type}, {"data.indent", Int64.Type}, {"data.isAgile", type logical}, {"data.isCritical", type logical}, {"data.isDurationLocked", type logical}, {"data.isLevelingExcluded", type logical}, {"data.isReady", type logical}, {"data.isStatusComplete", type logical}, {"data.isWorkRequiredLocked", type logical}, {"data.lastConditionNoteID", type text}, {"data.lastNoteID", type text}, {"data.lastUpdateDate", type text}, {"data.lastUpdatedByID", type text}, {"data.levelingStartDelay", Int64.Type}, {"data.levelingStartDelayMinutes", Int64.Type}, {"data.milestoneID", type text}, {"data.numberOfChildren", Int64.Type}, {"data.numberOpenOpTasks", Int64.Type}, {"data.originalDuration", Int64.Type}, {"data.originalWorkRequired", Int64.Type}, {"data.parentID", type text}, {"data.parentLag", Int64.Type}, {"data.parentLagType", type text}, {"data.percentComplete", Int64.Type}, {"data.personal", type logical}, {"data.plannedBillableExpenseCost", Int64.Type}, {"data.plannedCompletionDate", type text}, {"data.plannedCost", Int64.Type}, {"data.plannedDuration", Int64.Type}, {"data.plannedDurationMinutes", Int64.Type}, {"data.plannedExpenseCost", Int64.Type}, {"data.plannedLaborCost", Int64.Type}, {"data.plannedNonBillableExpenseCost", Int64.Type}, {"data.plannedRevenue", Int64.Type}, {"data.plannedStartDate", type text}, {"data.previousStatus", type text}, {"data.priority", Int64.Type}, {"data.progressStatus", type text}, {"data.projectID", type text}, {"data.projectedCompletionDate", type text}, {"data.projectedDurationMinutes", Int64.Type}, {"data.projectedStartDate", type text}, {"data.recurrenceNumber", Int64.Type}, {"data.referenceNumber", Int64.Type}, {"data.remainingDurationMinutes", Int64.Type}, {"data.resourceScope", type text}, {"data.revenueType", type text}, {"data.roleID", type text}, {"data.securityRootID", type text}, {"data.securityRootObjCode", type text}, {"data.slackDate", type date}, {"data.spi", Int64.Type}, {"data.status", type text}, {"data.statusUpdate", type text}, {"data.storyPoints", Int64.Type}, {"data.taskConstraint", type text}, {"data.taskNumber", Int64.Type}, {"data.teamID", type text}, {"data.templateTaskID", type text}, {"data.trackingMode", type text}, {"data.version", Int64.Type}, {"data.wbs", type text}, {"data.work", type number}, {"data.workRequired", Int64.Type}, {"data.parameterValues.DE:Change Timeline", type text}, {"data.parameterValues.DE:Client Facing", type text}, {"data.parameterValues.DE:On Time Status", type text}, {"data.parameterValues.DE:Current Due Date", type date}, {"data.parameterValues.DE:Planned Completion No Time", type date}, {"data.parameterValues.DE:Partner Contract Path", type text}, {"data.parameterValues.DE:Disqualifiers & Concerns", type text}, {"data.parameterValues.DE:Client Eligibility Type", type text}, {"data.parameterValues.DE:Client Manager", type text}, {"data.parameterValues.DE:Migration Category at Migration", type text}, {"data.parameterValues.DE:TPM Lead", type text}, {"data.parameterValues.DE:Client or Access Code", type text}, {"data.parameterValues.DE:Invited to Migrate", type text}, {"data.parameterValues.DE:Client Agreed For Migration", type text}, {"data.parameterValues.DE:Migration Category", type text}, {"data.parameterValues.DE:MyS Guage Count As", Int64.Type}, {"data.parameterValues.DE:Date Preference For Migration", type date}})
in
  #"Changed column type";
